{
    "name": "Escuela",
    "summary": "LEULIT ESCUELA",
    "description": "\n    ",
    "author": "Leulit S.L.",
    "website": "http://www.leulit.com",
    "category": "leulit",
    "version": "17.0.1.0.0",
    "depends": [
        "leulit",
        "leulit_planificacion",
        "leulit_operaciones"
    ],
    "data": [
        "groups.xml",
        "security.xml",
        "views/leulit_curso_template.xml",
        "views/leulit_curso.xml",
        "views/leulit_report_checklist_curso.xml",
        "views/leulit_asignatura.xml",
        "views/leulit_profesor.xml",
        "views/leulit_resource.xml",
        "views/leulit_parte_escuela.xml",
        "views/leulit_alumno.xml",
        "views/leulit_rel_alumno_curso.xml",
        "views/leulit_silabus.xml",
        "views/leulit_vuelo.xml",
        "views/leulit_popup_rel_parte_escuela_cursos_alumnos.xml",
        "views/leulit_rel_parte_escuela_cursos_alumnos.xml",
        "views/leulit_wizard_report_practicas_curso.xml",
        "views/leulit_wizard_report_teoricas_curso.xml",
        "views/leulit_informes_historial_popup.xml",
        "views/leulit_perfil_formacion_print_wizard.xml",
        "report/leulit_report_curso_pf.xml",
        "report/ir_actions_report.xml",
        "views/leulit_pf_accion.xml",
        "views/leulit_perfil_formacion.xml",
        "views/leulit_perfil_formacion_curso.xml",
        "views/leulit_report_pf_curso.xml",
        "views/popup_replicar_cursos_pf.xml",
        "views/leulit_rel_alumno_evaluacion.xml",
        "views/leulit_perfil_formacion_accion.xml",
        "views/leulit_wizard_informe_progreso_alumnos.xml",
        "data/leulit_perfil_formacion_check_rojos.xml",
        "data/leulit_perfil_formacion_check_rojos_hoy.xml",
        "data/leulit_parte_escuela_check_pendientes.xml",
        "data/leulit_parte_escuela_check_sin_verificar.xml",
        "menu.xml"
    ],
    "demo": [],
    "assets": {
        "web.assets_backend": [
            "leulit_escuela/static/src/components/tabla_resumen_asignaturas/tabla_resumen_asignaturas.js",
            "leulit_escuela/static/src/components/tabla_resumen_asignaturas/tabla_resumen_asignaturas.xml",
            "leulit_escuela/static/src/components/tabla_resumen_asignaturas/tabla_resumen_asignaturas.css",
            "leulit_escuela/static/src/components/tabla_resumen_asignaturas/tabla_resumen_asignaturas_practicas.js",
            "leulit_escuela/static/src/components/tabla_resumen_asignaturas/tabla_resumen_asignaturas_practicas.xml",
        ],
    },
    "installable": True,
    "auto_install": False,
    "application": True,
    "license": "LGPL-3"
}
