{
    "name": "Seguridad",
    "summary": "LEULIT SEGURIDAD",
    "description": "\n    ",
    "author": "Leulit S.L.",
    "website": "http://www.leulit.com",
    "category": "leulit",
    "version": "17.0.1.0.0",
    "depends": [
        "leulit",
        "leulit_operaciones",
        "leulit_taller",
        "mgmtsystem_audit"
    ],
    "data": [
        "groups.xml",
        "security.xml",
        "sequences.xml",
        "data/cron_anotacion_technical_log.xml",
        "views/leulit_anomalia.xml",
        "views/leulit_anotacion_techincal_log.xml",
        "report/leulit_informe_anomalia.xml",
        "report/leulit_informe_anotacion_technical_log.xml",
        "report/ir_actions_report.xml",
        "views/leulit_vuelo.xml",
        "views/maintenance_request.xml",
        "views/leulit_wizard_asign_anomalia.xml",
        "views/mgmtsystem_audit.xml",
        "views/leulit_audit_question.xml",
        "views/leulit_procedure_audit_question.xml",
        "views/mgmtsystem_nonconformity.xml",
        "views/mgmtsystem_action.xml",
        "menu.xml"
    ],
    "demo": [],
    "css": [],
    "installable": True,
    "auto_install": False,
    "application": True,
    "license": "LGPL-3"
}
