from . import stock_lot
from . import stock_production_lot_automatizaciones
from . import stock_move_line
from . import stock_move
from . import product_product
from . import stock_picking
from . import ir_attachment
from . import maintenance_equipment
from . import leulit_calibracion
from . import stock_install
from . import stock_uninstall
from . import stock_move_certificate
from . import stock_move_scrap
from . import stock_warehouse_orderpoint
from . import stock_warehouse_orderpoint_automatizaciones
from . import stock_quant
from . import stock_location
from . import stock_quant_package
from . import leulit_asignar_caja
from . import leulit_rel_formone_lot
from . import purchase_order_line
from . import purchase_order
from . import leulit_maintenance_boroscopia
from . import maintenance_plan