from . import res_partner
from . import leulit_parte_escuela
from . import leulit_curso_template
from . import leulit_curso
from . import leulit_perfil_formacion
from . import popup_perfil_formacion
from . import leulit_perfil_formacion_curso
from . import leulit_perfil_formacion_curso_last_done
from . import popup_replicar_cursos_pf
from . import leulit_report_pf_curso
from . import leulit_accion
from . import leulit_pf_accion
from . import leulit_pf_accion_last_done
from . import leulit_popup_replicar_pf_acciones
from . import leulit_perfil_formacion_automatizaciones
from . import leulit_parte_escuela_automatizaciones
from . import leulit_vuelo
from . import leulit_silabus
from . import leulit_resource
from . import leulit_rel_parte_escuela_cursos_alumnos
from . import leulit_popup_rel_parte_escuela_cursos_alumnos
from . import leulit_rel_alumno_evaluacion
from . import leulit_rel_alumno_documentacion
from . import leulit_rel_alumno_curso
from . import leulit_profesor
from . import leulit_perfil_formacion_accion
from . import leulit_perfil_formacion_accion_last_done
from . import popup_replicar_acciones_pf
from . import ir_attachment
from . import leulit_actividad_vuelo
from . import leulit_alumno
from . import leulit_alumno_horas_facturadas
from . import leulit_alumno_ingreso
from . import leulit_asignatura
from . import leulit_wizard_report_practicas_curso
from . import leulit_wizard_report_teoricas_curso
from . import leulit_informes_historial_popup
from . import leulit_perfil_formacion_print_wizard
from . import leulit_report_curso_pf