from . import mgmtsystem_asset
from . import mgmtsystem_audit_report
from . import mgmtsystem_catalogs
from . import mgmtsystem_dashboard
from . import mgmtsystem_document
from . import mgmtsystem_notification_cron
from . import mgmtsystem_risk
from . import mgmtsystem_risk_bulk_wizard
from . import mgmtsystem_risk_export_wizard
from . import mgmtsystem_risk_reject_wizard
from . import res_config_settings
