{
    "name": "Almacén",
    "summary": "Leulit - Almacén",
    "description": "\n    ",
    "author": "Leulit S.L.",
    "website": "http://www.leulit.com",
    "category": "leulit",
    "version": "17.0.1.0.0",
    "depends": [
        "leulit",
        "leulit_taller",
        "sale_product_configurator",
        "product_expiry"
    ],
    "data": [
        "groups.xml",
        "security.xml",
        "views/stock_move_line.xml",
        "views/stock_lot.xml",
        "views/stock_picking.xml",
        "views/product_product.xml",
        "views/leulit_etiquetas.xml",
        "views/maintenance_equipment.xml",
        # "views/stock_warehouse_orderpoint.xml",
        "views/leulit_calibracion.xml",
        "views/stock_install.xml",
        "views/stock_uninstall.xml",
        "views/stock_move_certificate.xml",
        "views/stock_move_scrap.xml",
        "views/stock_quant.xml",
        "views/leulit_rel_formone_lot.xml",
        "views/purchase_order.xml",
        "views/leulit_maintenance_boroscopia.xml",
        "views/maintenance_plan.xml",
        "data/stock_warehouse_orderpoint_notify_stock_minimo.xml",
        "data/stock_production_lot_notify_expiration_date.xml",
        "menu.xml"
    ],
    "demo": [],
    "css": [],
    "installable": True,
    "auto_install": False,
    "application": True,
    "license": "LGPL-3"
}
